project:
  type: website
  output-dir: docs
  
website:
  title: "BIL POC2 Fueling Adaptation"
  navbar:
    logo: /img/logo_bw.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: team.qmd
        text: Team 
    right:
      - text: More
        menu:
          - href: misc/comparison_map.qmd
            text: Capacity vs need mockup
          - href: misc/counties_map.qmd
            text: WCS counties reference
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023"

format:
  html:
    theme: united
    toc: true
    grid:
      body-width: 500px
      margin-width: 350px

editor: source

execute:
  freeze: auto

