project:
  type: website
  output-dir: docs
  
website:
  title: "BIL POC2 Fueling Adaptations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: team.qmd
        text: Team 
    right:
      - text: More
        menu: 
        - notebooks.qmd
        - map.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023"

format:
  html:
    theme: united
    toc: true

editor: source

